import Head from "next/head";
import Image from "next/image";
import styles from "./Home.module.scss";
import Layout from "../components/Layout/Layout";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Work Wiz</title>
        <meta name="description" content="Generated by Work Wiz" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.Home}>
          <div>メインコンテンツー</div>
          <Link href="/login">
            ログイン
          </Link>
        </main>
      </Layout>
    </>
  );
}
